version: '3'

services:
  postgres:
    image: postgres:14
    container_name: shiori-db
    networks:
      - shiori-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shiori_development
      POSTGRES_USER: shiori
      POSTGRES_PASSWORD: rootpass

  redis:
    image: redis:6
    container_name: shiori-redis
    networks:
      - shiori-net
    ports:
      - 6379:6379

networks:
  shiori-net:
