default: &default
  secret_key_base: dummy
  api_token_secret: dummy

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_token_secret: <%= ENV["API_TOKEN_SECRET"] %>
